import {StyleSheet,DefaultT} from 'react-native';

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  collumn: {
    flexDirection: 'row',
  },
  
  displayValue: {
    fontSize: 40,
    marginBottom: 30
  },
  numbers: {
    justifyContent: 'center',
    textAlign: 'center',
    width:70,
    height: 60,
    borderRadius:50,
    shadowColor: 'black',
    shadowOffset: { width: 70, height: 60 }, 
    shadowOpacity: 1,  
    shadowRadius: 1,
    elevation: 20, 
    marginLeft:2,
    marginRight:2,
    marginBottom:10,
    backgroundColor: 'white',
    fontSize: 40,
  },
  zero: {
    justifyContent: 'center',
    textAlign: 'center',
    width:160,
    height: 60,
    borderRadius:50,
    shadowColor: 'black',
    shadowOffset: { width: 70, height: 60 }, 
    shadowOpacity: 1,  
    shadowRadius: 1,
    elevation: 20, 
    marginLeft:2,
    marginRight:2,
    marginBottom:10,
    backgroundColor: 'white',
    fontSize: 40,
  },
  operation: {
    justifyContent: 'center',
    textAlign: 'center',
    width:70,
    height: 60,
    borderRadius:50,
    shadowColor: 'black',
    shadowOffset: { width: 70, height: 60 }, 
    shadowOpacity: 1,  
    shadowRadius: 1,
    elevation: 20, 
    marginLeft:2,
    marginRight:2,
    marginBottom:10,
    backgroundColor: 'white',
    fontSize: 40,
    color:'orange'
  },
  equal: {
    justifyContent: 'center',
    textAlign: 'center',
    width:55,
    height: 60,
    borderRadius:50,
    shadowColor: 'black',
    shadowOffset: { width: 70, height: 60 }, 
    shadowOpacity: 1,  
    shadowRadius: 1,
    elevation: 20, 
    marginLeft:2,
    marginRight:2,
    marginBottom:10,
    backgroundColor: 'orange',
    color: 'white',
    fontSize: 40,
  },
  clear: {
    justifyContent: 'center',
    textAlign: 'center',
    width:286,
    height: 60,
    borderRadius:50,
    shadowColor: 'black',
    shadowOffset: { width: 70, height: 60 }, 
    shadowOpacity: 1,  
    shadowRadius: 1,
    elevation: 20, 
    marginLeft:2,
    marginRight:2,
    marginBottom:10,
    backgroundColor: 'white',
    fontSize: 40,
  },
});
